Update Products_Suppliers set ProductId =1  where ProductSupplierId =1
Update Products_Suppliers set ProductId =1  where ProductSupplierId =2
Update Products_Suppliers set ProductId =8  where ProductSupplierId =3
Update Products_Suppliers set ProductId =1  where ProductSupplierId =4
Update Products_Suppliers set ProductId =8  where ProductSupplierId =6
Update Products_Suppliers set ProductId =1  where ProductSupplierId =7
Update Products_Suppliers set ProductId =3  where ProductSupplierId =8
Update Products_Suppliers set ProductId =7  where ProductSupplierId =9
Update Products_Suppliers set ProductId =8  where ProductSupplierId =10
Update Products_Suppliers set ProductId =8  where ProductSupplierId =11
Update Products_Suppliers set ProductId =5  where ProductSupplierId =12
Update Products_Suppliers set ProductId =1  where ProductSupplierId =13
Update Products_Suppliers set ProductId =8  where ProductSupplierId =14
Update Products_Suppliers set ProductId =8  where ProductSupplierId =15
Update Products_Suppliers set ProductId =1  where ProductSupplierId =16
Update Products_Suppliers set ProductId =1  where ProductSupplierId =19
Update Products_Suppliers set ProductId =3  where ProductSupplierId =20
Update Products_Suppliers set ProductId =1  where ProductSupplierId =23
Update Products_Suppliers set ProductId =5  where ProductSupplierId =24
Update Products_Suppliers set ProductId =3  where ProductSupplierId =25
Update Products_Suppliers set ProductId =8  where ProductSupplierId =26
Update Products_Suppliers set ProductId =8  where ProductSupplierId =28
Update Products_Suppliers set ProductId =1  where ProductSupplierId =29
Update Products_Suppliers set ProductId =1  where ProductSupplierId =30
Update Products_Suppliers set ProductId =5  where ProductSupplierId =31
Update Products_Suppliers set ProductId =3  where ProductSupplierId =32
Update Products_Suppliers set ProductId =5  where ProductSupplierId =33
Update Products_Suppliers set ProductId =1  where ProductSupplierId =34
Update Products_Suppliers set ProductId =5  where ProductSupplierId =35
Update Products_Suppliers set ProductId =8  where ProductSupplierId =36
Update Products_Suppliers set ProductId =5  where ProductSupplierId =37
Update Products_Suppliers set ProductId =9  where ProductSupplierId =39
Update Products_Suppliers set ProductId =8  where ProductSupplierId =40
Update Products_Suppliers set ProductId =5  where ProductSupplierId =41
Update Products_Suppliers set ProductId =5  where ProductSupplierId =42
Update Products_Suppliers set ProductId =1  where ProductSupplierId =43
Update Products_Suppliers set ProductId =1  where ProductSupplierId =44
Update Products_Suppliers set ProductId =9  where ProductSupplierId =45
Update Products_Suppliers set ProductId =8  where ProductSupplierId =46
Update Products_Suppliers set ProductId =9  where ProductSupplierId =47
Update Products_Suppliers set ProductId =8  where ProductSupplierId =48
Update Products_Suppliers set ProductId =4  where ProductSupplierId =49
Update Products_Suppliers set ProductId =9  where ProductSupplierId =50
Update Products_Suppliers set ProductId =8  where ProductSupplierId =51
Update Products_Suppliers set ProductId =5  where ProductSupplierId =52
Update Products_Suppliers set ProductId =4  where ProductSupplierId =53
Update Products_Suppliers set ProductId =8  where ProductSupplierId =54
Update Products_Suppliers set ProductId =3  where ProductSupplierId =55
Update Products_Suppliers set ProductId =1  where ProductSupplierId =56
Update Products_Suppliers set ProductId =8  where ProductSupplierId =57
Update Products_Suppliers set ProductId =2  where ProductSupplierId =58
Update Products_Suppliers set ProductId =1  where ProductSupplierId =59
Update Products_Suppliers set ProductId =5  where ProductSupplierId =60
Update Products_Suppliers set ProductId =3  where ProductSupplierId =61
Update Products_Suppliers set ProductId =2  where ProductSupplierId =63
Update Products_Suppliers set ProductId =1  where ProductSupplierId =64
Update Products_Suppliers set ProductId =9  where ProductSupplierId =65
Update Products_Suppliers set ProductId =8  where ProductSupplierId =66
Update Products_Suppliers set ProductId =8  where ProductSupplierId =67
Update Products_Suppliers set ProductId =4  where ProductSupplierId =68
Update Products_Suppliers set ProductId =9  where ProductSupplierId =69
Update Products_Suppliers set ProductId =4  where ProductSupplierId =70
Update Products_Suppliers set ProductId =4  where ProductSupplierId =71
Update Products_Suppliers set ProductId =1  where ProductSupplierId =72
Update Products_Suppliers set ProductId =10  where ProductSupplierId =73
Update Products_Suppliers set ProductId =1  where ProductSupplierId =74
Update Products_Suppliers set ProductId =4  where ProductSupplierId =75
Update Products_Suppliers set ProductId =8  where ProductSupplierId =76
Update Products_Suppliers set ProductId =1  where ProductSupplierId =78
Update Products_Suppliers set ProductId =2  where ProductSupplierId =79
Update Products_Suppliers set ProductId =6  where ProductSupplierId =80
Update Products_Suppliers set ProductId =4  where ProductSupplierId =81
Update Products_Suppliers set ProductId =5  where ProductSupplierId =82
Update Products_Suppliers set ProductId =5  where ProductSupplierId =83
Update Products_Suppliers set ProductId =6  where ProductSupplierId =84
Update Products_Suppliers set ProductId =1  where ProductSupplierId =87
Update Products_Suppliers set ProductId =1  where ProductSupplierId =90
Update Products_Suppliers set ProductId =4  where ProductSupplierId =93
